# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prism < Formula
  desc "A colorful TUI terminal multiplexer with tab-per-project panes"
  homepage "https://github.com/nowgnas/prism"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nowgnas/prism/releases/download/v0.1.3/prism_0.1.3_darwin_amd64.tar.gz"
      sha256 "7279cbf5e5da31b8155b4a42b997f4648fcb1340d81db383fd21d3768d453249"

      define_method(:install) do
        bin.install "prism"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nowgnas/prism/releases/download/v0.1.3/prism_0.1.3_darwin_arm64.tar.gz"
      sha256 "31c35b194cea0dd60b47c2c7e0bc5c4a527ff6ae1ad0c983e303778129dc66ff"

      define_method(:install) do
        bin.install "prism"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nowgnas/prism/releases/download/v0.1.3/prism_0.1.3_linux_amd64.tar.gz"
      sha256 "822f4f39afaae589ca01d69c7238b0ec925b1e66392b5ef95cce3d4ca33accdc"
      define_method(:install) do
        bin.install "prism"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nowgnas/prism/releases/download/v0.1.3/prism_0.1.3_linux_arm64.tar.gz"
      sha256 "736f053487e6d20d8c8531c61dafb858f6c4f1dab2ed12e6eafe6fdbbdb35302"
      define_method(:install) do
        bin.install "prism"
      end
    end
  end

  test do
    system "#{bin}/prism --version"
  end
end
